# Writes the build id header.  Run as a script from a build-time custom
# command, so the revisions in it are the ones being compiled rather than the
# ones the tree happened to be configured at:
#
#   cmake -DBMMO_ROOT=<repo> -DBMMO_HEADER=<out.h> -P cmake/WriteBuildId.cmake
#
# A working tree with uncommitted changes gets "-dirty": two peers built from
# the same commit but different working trees are not the same build, and the
# server's session handshake compares these strings.

function(_bmmo_revision dir out)
    set(_rev "unknown")
    execute_process(COMMAND git -C "${dir}" rev-parse --short=12 HEAD
            OUTPUT_VARIABLE _hash OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET RESULT_VARIABLE _status)
    if (_status EQUAL 0 AND _hash)
        set(_rev "${_hash}")
        execute_process(COMMAND git -C "${dir}" status --porcelain
                OUTPUT_VARIABLE _dirt OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if (_dirt)
            set(_rev "${_rev}-dirty")
        endif ()
    endif ()
    set(${out} "${_rev}" PARENT_SCOPE)
endfunction()

if (BMMO_BUILD_ID)
    # A build from an export has no git to ask.  Packagers and CI can pass the
    # id they know instead of shipping binaries that call themselves unknown.
    set(_build_id "${BMMO_BUILD_ID}")
else ()
    _bmmo_revision("${BMMO_ROOT}/submodule/Ballanced" _engine_rev)
    _bmmo_revision("${BMMO_ROOT}" _bmmo_rev)
    set(_build_id "ballanced-${_engine_rev}+bmmo-${_bmmo_rev}")
endif ()

file(WRITE "${BMMO_HEADER}.tmp"
"// Generated by cmake/WriteBuildId.cmake before every build - do not edit.\n"
"#pragma once\n"
"\n"
"// \"ballanced-<engine revision>+bmmo-<repository revision>\".  The engine half\n"
"// is what decides whether two peers simulate alike; the server compares it\n"
"// against every client's before a physics session may start.\n"
"#define BMMO_PHYSICS_BUILD_ID \"${_build_id}\"\n")

# Copy only when it changed: an unchanged id must not rebuild the engine.
configure_file("${BMMO_HEADER}.tmp" "${BMMO_HEADER}" COPYONLY)
file(REMOVE "${BMMO_HEADER}.tmp")
