name: Client

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'BallanceMMOServer/**'
      - '.git*'
      - 'README.md'
      - '.github/workflows/server.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'BallanceMMOServer/**'
      - '.git*'
      - 'README.md'
      - '.github/workflows/server.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-client:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{github.workspace}}/submodule/vcpkg
    steps:
      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Fetch git submodules
        run: git submodule update --init --recursive

      - name: Download and extract BML 0.3.42
        working-directory: ${{github.workspace}}/BallanceMMOClient
        run: |
          curl -o BML-dev.zip -L https://github.com/yyc12345/BallanceModLoader/releases/download/0.3.42/BML-0.3.42-dev.zip
          tar -xf BML-dev.zip include lib
    
      - name: Download and extract BMLPlus 0.2.2
        working-directory: ${{github.workspace}}/BallanceMMOClient
        run: |
          curl -o BMLP-dev.zip -L https://github.com/yyc12345/BallanceModLoaderPlus/releases/download/v0.2.2/BMLP-0.2.2-dev.zip
          tar -xf BMLP-dev.zip ModLoader/Include ModLoader/Lib
          mv ModLoader/Include/BMLPlus include
          mkdir lib/BMLPlus
          mv ModLoader/Lib/BMLPlus.lib lib/BMLPlus

      - name: Setup Boost headers
        working-directory: ${{github.workspace}}/BallanceMMOClient
        run: |
          git clone https://github.com/scipy/boost-headers-only
          New-Item -ItemType Junction -Path include/boost -Target boost-headers-only/boost

      # Setup MSVC command prompt environment vars
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 861c33057553ee836e7061ffbdabc25ea343145d
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          vcpkgJsonGlob: vcpkg.json
          runVcpkgInstall: false

#      - name: vcpkg check / install dependencies
#        working-directory: ${{env.VCPKG_ROOT}}
#        run: vcpkg install --triplet x64-windows

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_MANIFEST_MODE=ON -DVCPKG_MANIFEST_DIR="${{github.workspace}}" -DVCPKG_TARGET_TRIPLET=x86-windows -DVIRTOOLS_SDK_FETCH_FROM_GIT=ON -DBUILD_SERVER=OFF -DBUILD_CLIENT=ON -A Win32

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#      - name: List build dir
#        working-directory: ${{github.workspace}}/build
#        run: dir

      # - name: Run post-build script
      #   working-directory: ${{github.workspace}}/build/BallanceMMOClient
      #   run: ${{github.workspace}}/build/BallanceMMOClient/postbuild.bat ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-windows
          path: build/BallanceMMOClient/${{env.BUILD_TYPE}}
