name: Client

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'BallanceMMOServer/**'
      - '.git*'
      - 'README.md'
      - '.github/workflows/server.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'BallanceMMOServer/**'
      - '.git*'
      - 'README.md'
      - '.github/workflows/server.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BML_VER: '0.3.43'
  BMLP_VER: '0.2.3'
  BOOST_VER: '1.80.0'

jobs:
  build-client:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{github.workspace}}/submodule/vcpkg
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Fetch git submodules
        run: git submodule update --init --recursive

      - name: Download and extract BML ${{env.BML_VER}}
        working-directory: ${{github.workspace}}/BallanceMMOClient
        run: |
          curl -o BML-dev.zip -L https://github.com/yyc12345/BallanceModLoader/releases/download/${{env.BML_VER}}/BML-${{env.BML_VER}}-dev.zip
          tar -xvf BML-dev.zip include lib
          mv lib/* lib/BML -ErrorAction Ignore
    
      - name: Download and extract BMLPlus ${{env.BMLP_VER}}
        working-directory: ${{github.workspace}}/BallanceMMOClient
        run: |
          curl -o BMLP-dev.zip -L https://github.com/yyc12345/BallanceModLoaderPlus/releases/download/v${{env.BMLP_VER}}/BMLP-${{env.BMLP_VER}}-dev.zip
          tar -xvf BMLP-dev.zip Include Lib/BMLPlus.lib Lib/ImGui.lib
          mkdir lib/BMLPlus
          mv lib/*.lib lib/BMLPlus

      - name: Download and setup Boost ${{env.BOOST_VER}} headers
        working-directory: ${{github.workspace}}/BallanceMMOClient
        # yes we know this is for linux, but we only need its headers so it's fine
        run: |
          $BOOST_VER_UNDERSCORES = "${{env.BOOST_VER}}".Replace('.', '_')
          curl -o boost.tar.gz -L "https://archives.boost.io/release/${{env.BOOST_VER}}/source/boost_$BOOST_VER_UNDERSCORES.tar.gz"
          tar -xzf boost.tar.gz boost_$BOOST_VER_UNDERSCORES/boost
          New-Item -ItemType Junction -Path include/boost -Target (Get-Item boost_$BOOST_VER_UNDERSCORES/boost).FullName

      # Setup MSVC command prompt environment vars
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win32

      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: b322364f06308bdd24823f9d8f03fe0cc86fd46f
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          vcpkgJsonGlob: vcpkg.json
          runVcpkgInstall: false

#      - name: vcpkg check / install dependencies
#        working-directory: ${{env.VCPKG_ROOT}}
#        run: vcpkg install --triplet x64-windows

      - name: Configure CMake
        run: |
          echo "`nfile(WRITE ${{github.workspace}}/version.txt `${BMMO_VER})" | Out-File CMakeLists.txt -Encoding "UTF8" -Append
          cmake -G Ninja -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_MANIFEST_MODE=ON -DVCPKG_MANIFEST_DIR="${{github.workspace}}" -DVCPKG_TARGET_TRIPLET=x86-windows -DVIRTOOLS_SDK_FETCH_FROM_GIT=ON -DBUILD_SERVER=OFF -DBUILD_CLIENT=ON
          echo "BMMO_VER=$(cat ${{github.workspace}}/version.txt)" >> $env:GITHUB_ENV
          echo "SHA_SHORT=$(git rev-parse --short ${{github.sha}})" >> $env:GITHUB_ENV

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#      - name: List build dir
#        working-directory: ${{github.workspace}}/build
#        run: dir

      - name: Run post-build actions
        working-directory: ${{github.workspace}}/build/BallanceMMOClient
        run: rm BallanceMMOClient.exp, BallanceMMOClient.lib

      - name: Test
        working-directory: ${{github.workspace}}
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-windows-${{env.BMMO_VER}}-${{env.SHA_SHORT}}
          path: build/BallanceMMOClient

      - name: Build spectation-enabled client
        run: |
          echo "`n#define BMMO_WITH_PLAYER_SPECTATION" | Out-File "BallanceMMOClient/bml_includes.h" -Encoding "UTF8" -Append
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          cd ${{github.workspace}}/build/BallanceMMOClient
          rm BallanceMMOClient.exp, BallanceMMOClient.lib

      - name: Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-spectator-windows-${{env.BMMO_VER}}-${{env.SHA_SHORT}}
          path: build/BallanceMMOClient
